# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=b'')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiserver.User')),
            ],
        ),
    ]
