# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0002_faceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiserver.User'),
        ),
    ]
